import AsyncStorage from "@react-native-async-storage/async-storage";
import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type AppLanguage = "ar" | "en" | "fr";
const STORAGE_KEY = "moudie.language.v3";
type Dictionary = Record<string, string>;
const dictionaries: Record<AppLanguage, Dictionary> = {
  en: {
    lobby: "Lobby",
    library: "Library",
    settings: "Settings",
    localPlay: "LOCAL PLAY",
    chooseSystem: "Choose your system",
    profile: "Profile & Preferences",
    username: "USERNAME",
    userId: "USER ID",
    save: "SAVE PROFILE",
    share: "SHARE USER ID",
    language: "LANGUAGE",
    title: "Your classic game lobby",
    choose: "Choose one of the four emulators.",
    changePhoto: "CHANGE PHOTO",
    newPlayer: "New player",
    about: "ABOUT CLASSIC ERA BY MOUDIE",
    policy: "PROGRAM POLICY",
    privacyPolicy: "PRIVACY POLICY",
    community: "JOIN OUR COMMUNITY (COMING SOON)",
    contact: "CONTACT US",
    help: "HELP & SUPPORT",
    suggestions: "SUGGESTIONS",
    localPrivacy: "LOCAL PRIVACY",
    privacyText: "Room credentials and your selected avatar remain on this device. Game files are not uploaded to our service.",
    nameShort: "Name is too short",
    nameShortText: "Enter at least two characters.",
    saved: "Saved",
    savedText: "Your player identity is ready for friend requests.",
    pendingText: "This section will be connected to the official service before public launch.",
    shareText: "Add me on Classic Era by Moudie. My User ID is",
    roomChat: "ROOM CHAT",
    send: "SEND",
    voice: "ROOM VOICE",
    micOn: "MIC ON",
    micOff: "MIC OFF",
    speakerOn: "SPEAKER ON",
    speakerOff: "SPEAKER OFF",
    preparingVoice: "Preparing room voice…",
    connectChat: "Connect to the room channel to enable chat.",
    writeMessage: "Write a message…",
    publicName: "Your public player name",
    createRoomError: "Could not create room",
    tryAgain: "Try again.",
    hostPublicLobby: "HOST PUBLIC LOBBY",
    createPrivateRoom: "CREATE PRIVATE ROOM",
    chooseEmulator: "CHOOSE AN EMULATOR",
    displayName: "DISPLAY NAME",
    voiceShort: "VOICE",
    chatShort: "CHAT",
    spectateShort: "SPECTATE",
    createRoomEnter: "CREATE ROOM & ENTER PLAYER",
    checkCode: "Check the code",
    roomCodeLength: "A room code has six letters or numbers.",
    addDisplayName: "Add a display name",
    joinError: "Could not join",
    checkCodeAndRetry: "Check the room code and try again.",
    joinPrivateRoom: "JOIN PRIVATE ROOM",
    roomCode: "ROOM CODE",
    joinAs: "HOW DO YOU WANT TO JOIN?",
    player: "PLAYER",
    controlGame: "You control the game",
    spectator: "SPECTATOR",
    watchTalkChat: "Watch, talk, and chat",
    joinRoom: "JOIN ROOM",
    createPrivateForFriends: "CREATE A PRIVATE ROOM FOR FRIENDS",
    readyError: "Could not mark ready",
    unsupportedFile: "Unsupported file",
    chooseFamicomFile: "Choose a legal Famicom game with the .nes extension.",
    choosePs1File: "Choose a complete PS1 .bin, .iso, .chd, or .pbp file. A CUE file is not selected here because it needs its companion BIN file.",
    choosePspFile: "Choose a PSP ISO, CSO, CHD, or PBP file.",
    unsupportedGameFile: "Could not read the selected file.",
    androidRequired: "Android APK required",
    ps1AndroidOnly: "The native PS1 player runs in the Android APK and is not available in the web preview.",
    pspAndroidOnly: "The native PSP player is available in the Android APK only.",
    biosAndroidOnly: "Local BIOS checking and installation are available in the Android APK only.",
    biosAdded: "BIOS added",
    biosStored: "The BIOS file was stored locally in the app. It is never uploaded or shared.",
    biosAddError: "Could not add BIOS",
    biosLegalDump: "Choose a legal dump with a supported name.",
    chooseFileError: "Could not choose the file",
    chooseGameError: "Could not choose game",
    choosePspGameError: "Could not choose PSP game",
    startGameError: "Could not start the game",
    startPspError: "Could not start PSP",
    startPs1Error: "Could not start the PS1 player",
    ps1GameError: "Try again and choose a game file from storage.",
    famicomGameError: "Try another Famicom game file.",
    noSavedState: "No saved state",
    noSavedStateText: "Start the game, then tap Local Save to create a save state for this game.",
    focusModeError: "Could not open focus mode",
    sessionStartError: "The session did not start",
    waitPlayersReady: "Wait until both players are ready.",
    ps1NetplayNeedsPlayers: "PS1 NetPlay requires every active player (2–8) to select the same complete game file and core.",
    pspNetplayNeedsSeat: "PSP NetPlay needs an assigned player seat and a verified room session.",
    readGameError: "Could not read the game file from storage.",
    readBrowserGameError: "Could not read the game file in the browser.",
    prepareEmulatorError: "Could not prepare the emulator screen.",
    waitOtherPlayer: "Wait until the other player connects to the room channel.",
    connectionIncomplete: "The connection between both devices is not complete yet.",
    androidRoomOnly: "Room verification is available in the Android APK only.",
    netplayNeedsSeat: "This room needs an assigned player seat and a verified multiplayer session.",
    brandName: "Classic Era by Moudie",
    slogan: "Old Equal Gold",
    voiceMode: "VOICE MODE",
    voicePushToTalk: "PUSH TO TALK",
    voiceOpenMic: "OPEN MIC",
    voiceChannel: "VOICE CHANNEL",
    voiceChannelRoom: "ROOM",
    voiceChannelTeam: "TEAM",
    voiceHoldToTalk: "HOLD TO TALK",
    voiceTeamNote: "Spectators listen only in the team channel.",
    voiceConnectedRoom: "Room voice connected — everyone in the room can talk.",
    voiceConnecting: "Connecting voice…",
    voiceReadyMuted: "Voice ready — microphone muted.",
    voiceWaitingRoom: "Voice is waiting for the room connection.",
    voiceMicPermission: "Microphone permission is required for room voice.",
    voiceBuiltInReady: "Built-in voice active.",
    voiceSetupFailed: "Voice channel setup failed.",
    voiceSfuUnavailable: "Voice SFU unavailable — using the built-in room channel.",
    voicePermissionTitle: "Room voice",
    voicePermissionMessage: "Classic Era needs microphone access for the room voice channel.",
    voiceAllow: "Allow",
    homeRetro: "CLASSIC GAMES, YOUR WAY",
    homeIntro: "Choose a play route first. Select your emulator, local game file, and settings only when you are ready to play.",
    homeLocalText: "Choose a system and play your legal game file on this device, with no online connection.",
    homePublicLobby: "PUBLIC LOBBY",
    homeCreateText: "Find an open classic-game lobby or host one for up to 4 players and 4 spectators (NES uses 2 players and 6 spectators).",
    homeJoinText: "Enter a simple invite code from your friends, then choose player or spectator mode.",
    homeTip: "Before a game starts, use Controller Settings and Screen Settings to save independent portrait and landscape layouts.",
    homeBrandSub: "FOUR SYSTEMS · NETPLAY",
    homeOpenSettings: "Open settings",
    libTitle: "Systems & Cores",
    libSubtitle: "Choose a play mode first, then select one of the four supported systems for your room or local session.",
    libPspDescription: "Choose a legal PSP game file from Local Play or a PSP room. Save states are stored on this device.",
    libNesDescription: "A room session starts after players verify the same game and compatible core.",
    libSegaDescription: "Choose a legal Sega game in Local Play. Your saves and control layout remain on this device.",
    libPs1Description: "Local saves, ISO support, and custom controls are available in the PS1 player.",
    libSaveReady: "LOCAL SAVE READY",
    libSaveLocalOnly: "LOCAL SAVE ONLY",
    libReady: "READY",
    libNoticeTitle: "YOUR FILES STAY LOCAL",
    libNoticeText: "Moudie NetPlay coordinates rooms and compatibility checks only. It does not include games or transfer your game files to other players.",
    commonBack: "Back",
    localSubtitle: "Select one of the four emulators. Your game files, saves, and control layouts stay on this device.",
    localNotice: "Every emulator supports separate portrait and landscape control layouts. Use EDIT to drag a control, then SIZE − / + or pinch to resize it.",
    lbLoadError: "Could not load public lobbies",
    lbLoadErrorBody: "Try refreshing in a moment.",
    lbNameAlert: "Add a display name",
    lbNameAlertBody: "Enter at least two characters before joining a public lobby.",
    lbJoinError: "Could not join public lobby",
    lbJoinErrorBody: "Refresh the lobby list and try again.",
    lbTitle: "PUBLIC LOBBY",
    lbFindSession: "FIND A CLASSIC SESSION",
    lbHeroText: "Join an open lobby. Standard systems support 4 players and 4 spectators; NES supports 2 players and 6 spectators.",
    lbDisplayName: "YOUR DISPLAY NAME",
    lbExample: "Example: Alex",
    lbJoinAs: "JOIN AS",
    lbOpenLobbies: "OPEN LOBBIES",
    lbRefresh: "REFRESH",
    lbChecking: "Checking open lobbies…",
    lbNoneYet: "NO OPEN LOBBIES YET",
    lbNoneText: "Host the first public session, or ask a friend for a private room code.",
    lbPlayersShort: "PLAYERS",
    lbSpectatorsShort: "SPECTATORS",
    lbReadyShort: "READY",
    lbJoinBtn: "JOIN",
    lbFull: "FULL",
    crDefaultLobbyName: "Classic Lobby",
    crDefaultSessionName: "Friends Session",
    crFallbackHost: "Player",
    crPublicSub: "Public lobbies are discoverable by system and open seats. Invite codes stay private.",
    crPrivateSub: "Choose the game system. Every system has a dedicated controller layout inside the player.",
    crLobbyName: "LOBBY NAME",
    crRoomName: "ROOM NAME",
    crLobbyExample: "Example: Weekend Retro",
    crRoomExample: "Example: Friday Night Race",
    crFriendsVisible: "Visible to your friends",
    crCapacityTitle: "ROOM CAPACITY",
    crMembersShort: "MEMBERS",
    crActivePlayersShort: "ACTIVE PLAYERS",
    crSpectatorsShort: "SPECTATORS",
    crNoteNes: "Famicom is limited to two active controller seats. The remaining room members can spectate, talk, and chat without occupying a controller seat.",
    crNoteStd: "The room keeps active play and spectators separate to reduce synchronization pressure. Spectators can watch, talk, and chat without occupying a controller seat.",
    jrPrivacyNote: "Your room code and membership stay on this device. Game files are never sent to the room.",
    rmSharePrefix: "Join",
    rmShareCodeLabel: "Room code",
    rmOpenError: "Could not open room",
    rmOpenErrorText: "This membership may be stored on another device, or the room is no longer available.",
    rmReturnLobby: "RETURN TO LOBBY",
    rmWaiting: "WAITING FOR PLAYERS",
    rmActive: "SESSION ACTIVE",
    rmPrivateRoom: "PRIVATE ROOM",
    rmInviteCode: "INVITE CODE",
    rmShareCode: "SHARE CODE",
    rmMembers: "ROOM MEMBERS",
    rmHostBadge: "PLAYER 1 · HOST",
    rmPlayerShort: "PLAYER",
    rmSpectatorStatus: "Watching and talking in the room",
    rmChecking: "Checking emulator",
    rmEnterFamicom: "ENTER FAMICOM SETTINGS",
    rmEnterPs1: "ENTER PS1 SETTINGS",
    rmEnterPsp: "ENTER PSP SETTINGS",
    rmEnterSega: "ENTER SEGA GENESIS SETTINGS",
    rmPrepTitle: "PLAYER PREPARATION",
    rmPrepText: "Text chat and voice are available while the room player is prepared:",
    rmReadyOutOf: "READY OUT OF",
    playDone: "DONE",
    playEdit: "EDIT",
    playEditHint: "The game screen and every control are independent. Drag or resize each item, then save a separate layout for this system and orientation.",
    playOnlineRoom: "ONLINE ROOM",
    playPressed: "Pressed:",
    playChatTitle: "TEXT CHAT",
    playChatHintLocal: "Local messages remain on this device.",
    playChatHintRoom: "Room messages are sent to connected members.",
    playOpenChat: "Open text chat",
    lsShownInApk: "Shown inside the Android APK",
    lsCoreRequired: "Android core required",
    lsInstallApk: "Install the full Android APK to run this emulator.",
    lsSelectError: "Could not select a game file.",
    lsUnexpected: "An unexpected error occurred while opening the game file.",
    lsHeader: "EMULATOR LIBRARY",
    lsNesSubtitle: "Classic controller · Up to 4 controller slots when supported",
    lsPs1Subtitle: "PCSX-ReARMed · Save states and full controller editing",
    lsPspSubtitle: "PPSSPP · PSP network profile for supported games",
    lsSegaSubtitle: "Genesis Plus GX · 3 or 6 button layouts",
    lsCheckingCore: "CHECKING CORE",
    lsCoreReady: "CORE READY",
    lsDownloadsFirst: "DOWNLOADS AT FIRST LAUNCH",
    lsHowTitle: "HOW THIS EMULATOR WORKS",
    lsHowText: "Choose a legal game file stored on your device. Moudie never uploads your game or BIOS. Configure portrait and landscape controls before playing; the game screen remains free of move and resize tools.",
    lsIsoNotice: "PS1 supports ISO files as well as BIN, CUE, CHD, and PBP.",
    lsExtPrefix: "Supported extensions:",
    lsOrientations: "Portrait and landscape play are both supported with independent controller layouts.",
    lsSaveNote: "Local save/load state is available from the in-game toolbar.",
    lsSettingsTitle: "EMULATOR SETTINGS",
    lsPlayOrientation: "PLAY ORIENTATION",
    lsScreenRatio: "SCREEN RATIO",
    lsPreparing: "PREPARING GAME…",
    lsChooseStart: "CHOOSE GAME & START",
    lsLegal: "By choosing a file, you confirm that you have the right to use it. Moudie does not include ROMs or BIOS files.",
    fcChooseGameFirst: "Choose a game first",
    fcOtherVerified: "The other player verified the game file. The host can start the session.",
    fcStateRestored: "The latest local game state was restored.",
    fcStateRestoreError: "Could not restore the latest local game state.",
    fcStateSaving: "Saving the game state locally…",
    fcSetupOpen: "Controller setup is open for this orientation. Drag or resize every control, then save and return to READY.",
    fcFocusErrorBody: "Could not open native focus mode.",
    fcHostSynced: "The host synchronized the game start.",
    fcSyncError: "Could not synchronize the game start. Reload the file and reconnect to the room.",
    fcDifferentFile: "The other player has a different game file or core version.",
    fcVerified: "Game compatibility verified. The host can start the two-player session.",
    fcConnectedVerifying: "Connected to the other device. Verifying the game file…",
    fcConnectionClosed: "Connection to the other player was closed.",
    fcConnectionError: "Could not complete the connection. Check that the other player opened the Famicom player.",
    fcConnectingChannel: "Connecting the room NetPlay channel…",
    fcChannelReady: "The room channel is ready. Wait for the other player to join and choose the same file.",
    fcChannelError: "Could not connect to the room. Check your internet connection and try again.",
    fcInterrupted: "Room connection interrupted; reconnecting automatically…",
    fcReconnecting: "Reconnecting to the room…",
    fcSyncingStart: "Game compatibility confirmed. Synchronizing the shared starting state…",
    fcSyncDelayed: "The shared Famicom state is delayed. Keep both players in the game, verify the same .nes file, then restart the room session.",
    fcWaitingConfirm: "Waiting for the other player to confirm the game file and core.",
    fcSyncingFromHost: "Synchronizing the shared Famicom state from the host…",
    fcRoomError: "The room reported an error while preparing Famicom NetPlay.",
    fcNetplayPrepareError: "Could not prepare the NetPlay connection.",
    fcLoadingLocal: "Loading the game locally on this device…",
    fcRunningLocal: "The game is running locally. Connect the other player after they choose the same game.",
    fcFileError: "Could not run this file. Try another compatible .nes file.",
    fcPreparingRoom: "Preparing the room connection…",
    fcConnectingHost: "Connecting to the host…",
    fcReserveError: "Could not reserve the room connection. Try again in a minute.",
    fcHostNotReady: "The host is not ready yet. Ask them to connect first.",
    fcRoomReady: "The room connection is ready. Wait for the second player to connect.",
    fcNetplayStartError: "Could not start NetPlay on this connection. Update the browser and try again.",
    fcMarkedReady: "Your game file is marked ready. Wait for the other player, then the host starts the session.",
    fcVerifyingBoth: "Verifying the file and core on both devices before starting…",
    fcSessionActive: "The two-player session is active. The host is Player 1 and the guest is Player 2.",
    fcConfirmingRole: "Confirming this device role in the room. Wait a moment, then press the button again.",
    fcStateSaved: "Game state saved locally.",
    fcSaveReturn: "SAVE & RETURN TO EMULATOR SETTINGS",
    fcBackToRoom: "BACK TO ROOM",
    fcSaveControls: "SAVE CONTROLS",
    fcConfigureControls: "CONFIGURE CONTROLS",
    fcOpeningSettings: "OPENING SETTINGS…",
    fcControllerSettings: "CONTROLLER SETTINGS",
    fcEyebrow: "FAMICOM · NETPLAY",
    fcGamePlayer: "GAME PLAYER",
    fcSubtitle: "Choose the same .nes file on both devices. The file stays local and is never uploaded or shared by Moudie NetPlay.",
    fcNoGame: "NO GAME SELECTED",
    fcEditMode: "Edit mode: drag or resize the controls, HUD, and game screen for this orientation, then save and return.",
    fcScreen: "SCREEN",
    fcLocal: "LOCAL",
    fcChangeFile: "CHANGE GAME FILE",
    fcChooseNes: "1. CHOOSE .NES FILE",
    fcLocalFile: "LOCAL FILE",
    fcScreenControls: "EMULATOR SCREEN & CONTROLS",
    fcConfigureScreen: "CONFIGURE CONTROLS & SCREEN",
    fcLocalSave: "LOCAL SAVE",
    fcLoadSave: "LOAD SAVE",
    fcNetplayStatus: "NETPLAY STATUS",
    fcPrepareHost: "2. PREPARE ROOM CONNECTION",
    fcConnectOther: "2. CONNECT TO OTHER PLAYER",
    fcConnectChannel: "2. CONNECT NETPLAY CHANNEL",
    fcOtherConnected: "OTHER PLAYER CONNECTED",
    fcWaitingOther: "WAITING FOR OTHER PLAYER",
    fcReadyConfirmed: "READY CONFIRMED",
    fcReady3: "3. READY",
    fcStartSession: "4. START SYNCHRONIZED SESSION",
    fcVerifiedWait: "VERIFIED. WAIT FOR THE HOST TO START THE SESSION.",
    fcChatHint: "Write a message to the other player.",
    fcLocalControls: "LOCAL CONTROLS",
    fcControls: "CONTROLS",
    fcControlsAfterStart: "CONTROLS APPEAR AFTER THE HOST STARTS PLAY",
    fcResetGame: "RESET GAME",
    fcHowToPlay: "HOW TO PLAY",
    fcHowWeb: "Browser NetPlay requires a stable connection and the same game file on both sides.",
    fcHowNative: "Choose the same .nes file, connect the NetPlay channel on both devices, then let the host start the session. Host controls are Player 1 and guest controls are Player 2.",
    pspInitialStatus: "Choose the same legal PSP file on both devices.",
    pspChannelConnected: "Room channel connected. Choose your local file and mark READY.",
    pspChannelDisconnected: "Room channel disconnected. Reconnecting automatically…",
    pspAllReady: "All active players are ready. Opening the synchronized PSP player…",
    pspWaitingVerify: "Waiting for the other player to verify the same file.",
    pspCheckingFingerprint: "Checking the local PSP file fingerprint…",
    pspPreparingCore: "Preparing the PSP core and local file now for a fast synchronized start…",
    pspCacheReady: "File, core, and local launch cache are ready. Tap READY after every active player selects the same file.",
    pspPickSupported: "Choose a supported legal PSP file from this device.",
    pspReadyConfirmed: "READY confirmed. The host can start when all active players use the same file.",
    pspCheckingBoth: "Checking both PSP files and the core before the shared start…",
    pspChip: "PSP ROOM",
    pspEyebrow: "PPSSPP CORE · ROOM NETPLAY",
    pspSubtitle: "Each player selects the same legal local PSP file. The room verifies its fingerprint without uploading the game.",
    pspRoomConnected: "ROOM CONNECTED",
    pspConnecting: "CONNECTING",
    pspSpectatorWait: "SPECTATOR OR WAITING FOR A PLAYER SLOT",
    pspChangeGame: "CHANGE PSP GAME",
    pspChooseGame: "1. CHOOSE PSP GAME",
    pspSettingsHint: "Configure a separate portrait and landscape layout before playing. Edit and resize controls never appear during the match.",
    pspConfigurePortrait: "CONFIGURE PORTRAIT CONTROLS",
    pspConfigureLandscape: "CONFIGURE LANDSCAPE CONTROLS",
    pspReady2: "2. READY",
    pspStartSession: "3. START SYNCHRONIZED PSP SESSION",
    pspRoomControls: "ROOM CONTROLS",
    pspRoomControlsText: "CHAT and MIC stay at the top of the player in landscape. Spectators remain in the room for voice and text chat.",
    p1InitialStatus: "Choose a PS1 game file from your device. The file stays local and is never uploaded.",
    p1AllReady: "All active players are ready. Opening the PS1 player at the shared start time…",
    p1CheckingFingerprint: "Checking the local PS1 game fingerprint to verify that the other player selected the same file…",
    p1PreparingCore: "Preparing the PS1 core and local file now for a fast synchronized start…",
    p1FingerprintReady: "The file, PS1 core, and fingerprint are ready. Tap READY for a fast synchronized start.",
    p1MarkedReady: "Your game is marked ready. Wait for all active players, then the host can start the session.",
    p1CheckingBoth: "Checking every active player's game file and core before sending the start signal…",
    p1NetplayPreparing: "Preparing PS1 NetPlay and assigning this device inside the room…",
    p1LocalPreparing: "Preparing the game file and opening PCSX-ReARMed…",
    p1NetplayOpen: "The PS1 player is open and linked to the room. Wait for the in-game verification message.",
    p1LocalOpen: "The local player is open. Returning from the game brings you back to this room.",
    p1StartErrorBody: "Could not start the PS1 player.",
    p1Title: "PlayStation 1 Player",
    p1Subtitle: "Local play inside Moudie NetPlay. The app does not include games or BIOS files; use only files you are legally entitled to use.",
    p1ReadyPreview: "Ready for the native player",
    p1FormatsPreview: "Supports BIN, ISO, CHD, and PBP",
    p1ChangeFile: "CHANGE PS1 GAME FILE",
    p1ChooseFile: "1. CHOOSE PS1 GAME FILE",
    p1ScreenSettings: "SCREEN & CONTROLLER SETTINGS",
    p1ScreenSettingsText: "Choose the layout first, then open controller calibration. Each direction, action button, chat, microphone, and screen profile is saved separately for portrait and landscape.",
    p1OpenLocal: "OPEN LOCAL PS1 PLAYER",
    p1NetplayTitle: "PS1 NetPlay",
    p1NetplayAllMatch: "Every active player selected the same game. You are Player",
    p1NetplayWaiting: "Waiting for READY and a matching file",
    p1ConfirmingStart: "CONFIRMING START…",
    p1StartAll: "3. START PS1 FOR EVERYONE",
    p1WaitingHost: "WAITING FOR HOST TO START",
    p1PlayerStatus: "PS1 PLAYER STATUS",
    p1CheckingCore: "Checking the local core…",
    p1BiosStatus: "BIOS STATUS",
    p1CheckingBios: "Checking local BIOS…",
    p1BiosNote: "Some games may start with HLE, but a compatible local BIOS improves PCSX-ReARMed compatibility and helps diagnose games that fail to start.",
    p1AddBios: "ADD LEGAL LOCAL BIOS",
    p1BetaLimit: "CURRENT BETA LIMIT",
    p1BetaText: "PS1 NetPlay starts only when every active player in the room uses a file with the same fingerprint. The game is never uploaded; the room transports controller input and a small initial state only.",
    segInitialStatus: "Choose the same local file on both devices.",
    segWaitingOther: "Waiting for the other player.",
    segCoreNotReady: "This Android core is not ready.",
    segCheckingFingerprint: "Checking the local game fingerprint…",
    segPreparingCore: "Preparing the emulator core and local file now for a fast synchronized start…",
    segRoom: "ROOM",
    segCopy: "Select the identical local game file on two devices. Moudie checks a fingerprint, synchronizes the start state, then relays only control inputs and state updates.",
    segSpectatorSlot: "SPECTATOR / NO ACTIVE PLAYER SLOT",
    segChooseFile: "1. CHOOSE GAME FILE",
    segStartSession: "3. START SYNCHRONIZED SESSION",
    introBootLabel: "Moudie NetPlay boot animation",
    introLoading: "LOADING…",
    introSkip: "SKIP INTRO",
  },
  ar: {
    lobby: "الرئيسية",
    library: "المكتبة",
    settings: "الإعدادات",
    localPlay: "اللعب المحلي",
    chooseSystem: "اختر المحاكي",
    profile: "الملف الشخصي والتفضيلات",
    username: "اسم المستخدم",
    userId: "رقم المستخدم",
    save: "حفظ الملف الشخصي",
    share: "مشاركة رقم المستخدم",
    language: "اللغة",
    title: "ردهة ألعابك الكلاسيكية",
    choose: "اختر أحد المحاكيات الأربعة.",
    changePhoto: "تغيير الصورة",
    newPlayer: "لاعب جديد",
    about: "نبذة عن Classic Era by Moudie",
    policy: "سياسة البرنامج",
    privacyPolicy: "سياسة الخصوصية",
    community: "الانضمام إلى مجتمعنا (قريبًا)",
    contact: "اتصل بنا",
    help: "المساعدة والدعم",
    suggestions: "الاقتراحات",
    localPrivacy: "الخصوصية المحلية",
    privacyText: "تبقى بيانات الغرفة والصورة المختارة على هذا الجهاز. لا يتم رفع ملفات الألعاب إلى خدمتنا.",
    nameShort: "الاسم قصير جدًا",
    nameShortText: "أدخل حرفين على الأقل.",
    saved: "تم الحفظ",
    savedText: "أصبحت هويتك جاهزة لإرسال طلبات الإضافة.",
    pendingText: "سيتم ربط هذا القسم بالخدمة الرسمية قبل الإطلاق العام.",
    shareText: "أضفني على Classic Era by Moudie. رقم المستخدم:",
    roomChat: "دردشة الغرفة",
    send: "إرسال",
    voice: "صوت الغرفة",
    micOn: "الميكروفون يعمل",
    micOff: "الميكروفون مغلق",
    speakerOn: "مكبر الصوت يعمل",
    speakerOff: "مكبر الصوت مغلق",
    preparingVoice: "جارٍ تجهيز صوت الغرفة…",
    connectChat: "اتصل بقناة الغرفة لتفعيل الدردشة.",
    writeMessage: "اكتب رسالة…",
    publicName: "اسم اللاعب الظاهر",
    createRoomError: "تعذر إنشاء الغرفة",
    tryAgain: "حاول مرة أخرى.",
    hostPublicLobby: "استضافة الردهة العامة",
    createPrivateRoom: "إنشاء غرفة خاصة",
    chooseEmulator: "اختر محاكيًا",
    displayName: "الاسم الظاهر",
    voiceShort: "صوت",
    chatShort: "دردشة",
    spectateShort: "مشاهدة",
    createRoomEnter: "إنشاء الغرفة والدخول للعب",
    checkCode: "تحقق من الرمز",
    roomCodeLength: "رمز الغرفة يتكون من ستة أحرف أو أرقام.",
    addDisplayName: "أضف اسمًا ظاهرًا",
    joinError: "تعذر الانضمام",
    checkCodeAndRetry: "تحقق من رمز الغرفة وحاول مرة أخرى.",
    joinPrivateRoom: "الانضمام إلى غرفة خاصة",
    roomCode: "رمز الغرفة",
    joinAs: "كيف تريد الانضمام؟",
    player: "لاعب",
    controlGame: "تتحكم في اللعبة",
    spectator: "مشاهد",
    watchTalkChat: "شاهد وتحدث ودردش",
    joinRoom: "انضمام إلى الغرفة",
    createPrivateForFriends: "إنشاء غرفة خاصة للأصدقاء",
    readyError: "تعذر تأكيد الجاهزية",
    unsupportedFile: "ملف غير مدعوم",
    chooseFamicomFile: "اختر لعبة Famicom قانونية بامتداد .nes.",
    choosePs1File: "اختر ملف PS1 كاملًا بامتداد .bin أو .iso أو .chd أو .pbp. لا يتم اختيار ملف CUE وحده لأنه يحتاج إلى ملف BIN المصاحب.",
    choosePspFile: "اختر ملف PSP بامتداد ISO أو CSO أو CHD أو PBP.",
    unsupportedGameFile: "تعذر قراءة الملف المحدد.",
    androidRequired: "يلزم استخدام تطبيق Android",
    ps1AndroidOnly: "يعمل مشغل PS1 الأصلي داخل تطبيق Android ولا يتوفر في المعاينة على الويب.",
    pspAndroidOnly: "يتوفر مشغل PSP الأصلي داخل تطبيق Android فقط.",
    biosAndroidOnly: "يتوفر فحص BIOS وتثبيته محليًا داخل تطبيق Android فقط.",
    biosAdded: "تمت إضافة BIOS",
    biosStored: "تم حفظ ملف BIOS محليًا داخل التطبيق، ولا يتم رفعه أو مشاركته مطلقًا.",
    biosAddError: "تعذر إضافة BIOS",
    biosLegalDump: "اختر نسخة قانونية باسم مدعوم.",
    chooseFileError: "تعذر اختيار الملف",
    chooseGameError: "تعذر اختيار اللعبة",
    choosePspGameError: "تعذر اختيار لعبة PSP",
    startGameError: "تعذر تشغيل اللعبة",
    startPspError: "تعذر تشغيل PSP",
    startPs1Error: "تعذر تشغيل مشغل PS1",
    ps1GameError: "حاول مرة أخرى واختر ملف لعبة من وحدة التخزين.",
    famicomGameError: "جرّب ملف لعبة Famicom آخر.",
    noSavedState: "لا توجد حالة محفوظة",
    noSavedStateText: "شغّل اللعبة ثم اضغط حفظ محلي لإنشاء حالة محفوظة لهذه اللعبة.",
    focusModeError: "تعذر فتح وضع التركيز",
    sessionStartError: "لم تبدأ الجلسة",
    waitPlayersReady: "انتظر حتى يصبح اللاعبان جاهزين.",
    ps1NetplayNeedsPlayers: "يتطلب PS1 NetPlay أن يختار جميع اللاعبين النشطين (2–8) ملف اللعبة والمحرك الكامل نفسيهما.",
    pspNetplayNeedsSeat: "يتطلب PSP NetPlay مقعد لاعب مخصصًا وجلسة غرفة تم التحقق منها.",
    readGameError: "تعذر قراءة ملف اللعبة من وحدة التخزين.",
    readBrowserGameError: "تعذر قراءة ملف اللعبة في المتصفح.",
    prepareEmulatorError: "تعذر تجهيز شاشة المحاكي.",
    waitOtherPlayer: "انتظر حتى يتصل اللاعب الآخر بقناة الغرفة.",
    connectionIncomplete: "لم يكتمل الاتصال بين الجهازين بعد.",
    androidRoomOnly: "يتوفر التحقق من الغرفة داخل تطبيق Android فقط.",
    netplayNeedsSeat: "تحتاج هذه الغرفة إلى مقعد لاعب مخصص وجلسة لعب جماعي تم التحقق منها.",
    brandName: "Classic Era by Moudie",
    slogan: "القديم يساوي الذهب",
    voiceMode: "وضع الصوت",
    voicePushToTalk: "اضغط للتحدث",
    voiceOpenMic: "ميكروفون مفتوح",
    voiceChannel: "قناة الصوت",
    voiceChannelRoom: "الغرفة",
    voiceChannelTeam: "الفريق",
    voiceHoldToTalk: "استمر بالضغط للتحدث",
    voiceTeamNote: "المشاهدون يسمعون فقط في قناة الفريق.",
    voiceConnectedRoom: "تم توصيل صوت الغرفة — يمكن للجميع التحدث.",
    voiceConnecting: "جارٍ توصيل الصوت…",
    voiceReadyMuted: "الصوت جاهز — الميكروفون مغلق.",
    voiceWaitingRoom: "ينتظر الصوت اتصال الغرفة.",
    voiceMicPermission: "إذن الميكروفون مطلوب لصوت الغرفة.",
    voiceBuiltInReady: "الصوت المدمج نشط.",
    voiceSetupFailed: "تعذر تجهيز قناة الصوت.",
    voiceSfuUnavailable: "خدمة الصوت غير متاحة — تُستخدم القناة المدمجة.",
    voicePermissionTitle: "صوت الغرفة",
    voicePermissionMessage: "يحتاج Classic Era إلى وصول الميكروفون لقناة صوت الغرفة.",
    voiceAllow: "السماح",
    homeRetro: "ألعاب كلاسيكية بطريقتك",
    homeIntro: "اختر مسار اللعب أولًا. حدد المحاكي وملف اللعبة المحلي والإعدادات عندما تكون جاهزًا للعب فقط.",
    homeLocalText: "اختر النظام وشغّل ملف لعبتك القانوني على هذا الجهاز دون اتصال بالإنترنت.",
    homePublicLobby: "الردهة العامة",
    homeCreateText: "ابحث عن ردهة مفتوحة للألعاب الكلاسيكية أو استضف واحدة حتى 4 لاعبين و4 مشاهدين (المنس لاعبان و6 مشاهدين).",
    homeJoinText: "أدخل رمز الدعوة البسيط من أصدقائك ثم اختر وضع اللاعب أو المشاهد.",
    homeTip: "قبل بدء اللعبة، استخدم إعدادات وحدة التحكم وإعدادات الشاشة لحفظ تخطيطات مستقلة للوضع العمودي والأفقي.",
    homeBrandSub: "أربعة أنظمة · لعب جماعي",
    homeOpenSettings: "فتح الإعدادات",
    libTitle: "الأنظمة والنوى",
    libSubtitle: "اختر وضع اللعب أولًا، ثم أحد الأنظمة الأربعة المدعومة لغرفتك أو جلستك المحلية.",
    libPspDescription: "اختر ملف لعبة PSP قانونيًا من اللعب المحلي أو غرفة PSP. تُحفظ حالات الحفظ على هذا الجهاز.",
    libNesDescription: "تبدأ جلسة الغرفة بعد أن يتحقق اللاعبون من نفس اللعبة والنواة المتوافقة.",
    libSegaDescription: "اختر لعبة Sega قانونية في اللعب المحلي. تبقى حفظياتك وتخطيط التحكم على هذا الجهاز.",
    libPs1Description: "الحفظ المحلي ودعم ISO وأزرار مخصصة متوفرة في مشغل PS1.",
    libSaveReady: "الحفظ المحلي جاهز",
    libSaveLocalOnly: "حفظ محلي فقط",
    libReady: "جاهز",
    libNoticeTitle: "ملفاتك تبقى محلية",
    libNoticeText: "يتولى Moudie NetPlay تنسيق الغرف وفحوص التوافق فقط. لا يتضمن ألعابًا ولا ينقل ملفات ألعابك إلى لاعبين آخرين.",
    commonBack: "رجوع",
    localSubtitle: "اختر أحد المحاكيات الأربعة. تبقى ملفات ألعابك وحفظياتك وتخطيطات التحكم على هذا الجهاز.",
    localNotice: "يدعم كل محاكي تخطيطات تحكم منفصلة للوضع العمودي والأفقي. استخدم تعديل لسحب الزر ثم الحجم − / + أو القرص لتغيير حجمه.",
    lbLoadError: "تعذر تحميل الردهات العامة",
    lbLoadErrorBody: "حاول التحديث بعد لحظات.",
    lbNameAlert: "أضف اسمًا ظاهرًا",
    lbNameAlertBody: "أدخل حرفين على الأقل قبل الانضمام إلى ردهة عامة.",
    lbJoinError: "تعذر الانضمام إلى الردهة العامة",
    lbJoinErrorBody: "حدّث قائمة الردهات وحاول مرة أخرى.",
    lbTitle: "الردهة العامة",
    lbFindSession: "ابحث عن جلسة كلاسيكية",
    lbHeroText: "انضم إلى ردهة مفتوحة. الأنظمة القياسية تدعم 4 لاعبين و4 مشاهدين، والمنس لاعبان و6 مشاهدين.",
    lbDisplayName: "اسمك الظاهر",
    lbExample: "مثال: أحمد",
    lbJoinAs: "انضمام بصفة",
    lbOpenLobbies: "ردهات مفتوحة",
    lbRefresh: "تحديث",
    lbChecking: "جارٍ البحث عن ردهات مفتوحة…",
    lbNoneYet: "لا توجد ردهات مفتوحة بعد",
    lbNoneText: "استضف أول جلسة عامة، أو اطلب من صديق رمز غرفة خاصة.",
    lbPlayersShort: "لاعبين",
    lbSpectatorsShort: "مشاهدين",
    lbReadyShort: "جاهز",
    lbJoinBtn: "انضمام",
    lbFull: "مكتملة",
    crDefaultLobbyName: "ردهة كلاسيكية",
    crDefaultSessionName: "جلسة أصدقاء",
    crFallbackHost: "لاعب",
    crPublicSub: "الردهات العامة قابلة للاكتشاف حسب النظام والمقاعد المتاحة. تبقى رموز الدعوة خاصة.",
    crPrivateSub: "اختر نظام اللعبة. لكل نظام تخطيط تحكم مخصص داخل المشغل.",
    crLobbyName: "اسم الردهة",
    crRoomName: "اسم الغرفة",
    crLobbyExample: "مثال: حماس نهاية الأسبوع",
    crRoomExample: "مثال: سباق ليلة الجمعة",
    crFriendsVisible: "يظهر لأصدقائك",
    crCapacityTitle: "سعة الغرفة",
    crMembersShort: "أعضاء",
    crActivePlayersShort: "لاعبين نشطين",
    crSpectatorsShort: "مشاهدين",
    crNoteNes: "فاميكوم محدود بمقعدَي تحكم نشطين. يمكن لبقية الأعضاء المشاهدة والتحدث والدردشة دون شغل مقعد تحكم.",
    crNoteStd: "تفصل الغرفة بين اللعب النشط والمشاهدة لتقليل ضغط المزامنة. يمكن للمشاهدين المشاهدة والتحدث والدردشة دون شغل مقعد تحكم.",
    jrPrivacyNote: "يبقى رمز غرفتك وعضويتك على هذا الجهاز. لا تُرسل ملفات الألعاب إلى الغرفة مطلقًا.",
    rmSharePrefix: "انضم إليّ في",
    rmShareCodeLabel: "رمز الغرفة",
    rmOpenError: "تعذر فتح الغرفة",
    rmOpenErrorText: "قد تكون العضوية محفوظة على جهاز آخر، أو لم تعد الغرفة متاحة.",
    rmReturnLobby: "العودة إلى الرئيسية",
    rmWaiting: "بانتظار اللاعبين",
    rmActive: "الجلسة نشطة",
    rmPrivateRoom: "غرفة خاصة",
    rmInviteCode: "رمز الدعوة",
    rmShareCode: "مشاركة الرمز",
    rmMembers: "أعضاء الغرفة",
    rmHostBadge: "لاعب 1 · المضيف",
    rmPlayerShort: "لاعب",
    rmSpectatorStatus: "يشاهد ويتحدث داخل الغرفة",
    rmChecking: "جارٍ فحص المحاكي",
    rmEnterFamicom: "الدخول إلى إعدادات فاميكوم",
    rmEnterPs1: "الدخول إلى إعدادات PS1",
    rmEnterPsp: "الدخول إلى إعدادات PSP",
    rmEnterSega: "الدخول إلى إعدادات سيجا جينيسيس",
    rmPrepTitle: "تجهيز اللاعب",
    rmPrepText: "الدردشة النصية والصوت متاحان أثناء تجهيز مشغل الغرفة:",
    rmReadyOutOf: "جاهز من أصل",
    playDone: "تم",
    playEdit: "تعديل",
    playEditHint: "شاشة اللعبة وكل زر مستقلون. اسحب أو غيّر حجم كل عنصر، ثم احفظ تخطيطًا منفصلًا لكل نظام ووضع عرض.",
    playOnlineRoom: "غرفة أونلاين",
    playPressed: "الزر المضغوط:",
    playChatTitle: "دردشة نصية",
    playChatHintLocal: "تبقى الرسائل المحلية على هذا الجهاز.",
    playChatHintRoom: "تُرسل رسائل الغرفة إلى الأعضاء المتصلين.",
    playOpenChat: "فتح الدردشة النصية",
    lsShownInApk: "تظهر داخل تطبيق Android",
    lsCoreRequired: "نواة Android مطلوبة",
    lsInstallApk: "ثبّت تطبيق Android الكامل لتشغيل هذا المحاكي.",
    lsSelectError: "تعذر اختيار ملف اللعبة.",
    lsUnexpected: "حدث خطأ غير متوقع أثناء فتح ملف اللعبة.",
    lsHeader: "مكتبة المحاكيات",
    lsNesSubtitle: "يد تحكم كلاسيكية · حتى 4 مقاعد تحكم عند الدعم",
    lsPs1Subtitle: "PCSX-ReARMed · حالات حفظ وتحرير كامل لأزرار التحكم",
    lsPspSubtitle: "PPSSPP · ملف شبكة PSP للألعاب المدعومة",
    lsSegaSubtitle: "Genesis Plus GX · تخطيطات 3 أو 6 أزرار",
    lsCheckingCore: "جارٍ فحص النواة",
    lsCoreReady: "النواة جاهزة",
    lsDownloadsFirst: "يُنزَّل عند أول تشغيل",
    lsHowTitle: "كيف يعمل هذا المحاكي",
    lsHowText: "اختر ملف لعبة قانونيًا محفوظًا على جهازك. لا يرفع Moudie لعبتك أو BIOS مطلقًا. جهّز تخطيطي العمودي والأفقي قبل اللعب؛ وتبقى شاشة اللعبة خالية من أدوات التحريك وتغيير الحجم.",
    lsIsoNotice: "يدعم PS1 ملفات ISO إضافة إلى BIN وCUE وCHD وPBP.",
    lsExtPrefix: "الامتدادات المدعومة:",
    lsOrientations: "اللعب العمودي والأفقي كلاهما مدعوم بتخطيطات تحكم مستقلة.",
    lsSaveNote: "الحفظ والتحميل المحلي متاحان من شريط الأدوات داخل اللعبة.",
    lsSettingsTitle: "إعدادات المحاكي",
    lsPlayOrientation: "وضع اللعب",
    lsScreenRatio: "نسبة الشاشة",
    lsPreparing: "جارٍ تجهيز اللعبة…",
    lsChooseStart: "اختر اللعبة وابدأ",
    lsLegal: "باختيارك الملف فإنك تؤكد حقك في استخدامه. لا يتضمن Moudie ملفات ROM أو BIOS.",
    fcChooseGameFirst: "اختر لعبة أولًا",
    fcOtherVerified: "تحقق اللاعب الآخر من ملف اللعبة. يمكن للمضيف بدء الجلسة.",
    fcStateRestored: "استُعيدت أحدث حالة حفظ محلية.",
    fcStateRestoreError: "تعذر استعادة أحدث حالة حفظ محلية.",
    fcStateSaving: "جارٍ حفظ حالة اللعبة محليًا…",
    fcSetupOpen: "شاشة تهيئة الأزرار مفتوحة لهذا الاتجاه. اسحب أو غيّر حجم كل زر، ثم احفظ وعُد إلى جاهز.",
    fcFocusErrorBody: "تعذر فتح وضع التركيز الأصلي.",
    fcHostSynced: "زامن المضيف بداية اللعبة.",
    fcSyncError: "تعذرت مزامنة بداية اللعبة. أعد تحميل الملف واتصل بالغرفة من جديد.",
    fcDifferentFile: "يمتلك اللاعب الآخر ملف لعبة أو إصدار نواة مختلفًا.",
    fcVerified: "تم التحقق من توافق اللعبة. يمكن للمضيف بدء جلسة اللاعبين.",
    fcConnectedVerifying: "تم الاتصال بالجهاز الآخر. جارٍ التحقق من ملف اللعبة…",
    fcConnectionClosed: "أُغلق الاتصال باللاعب الآخر.",
    fcConnectionError: "تعذر إكمال الاتصال. تأكد من أن اللاعب الآخر فتح مشغل فاميكوم.",
    fcConnectingChannel: "جارٍ توصيل قناة NetPlay للغرفة…",
    fcChannelReady: "قناة الغرفة جاهزة. انتظر انضمام اللاعب الآخر واختياره الملف نفسه.",
    fcChannelError: "تعذر الاتصال بالغرفة. تحقق من اتصالك بالإنترنت وحاول مرة أخرى.",
    fcInterrupted: "انقطع اتصال الغرفة؛ جارٍ إعادة الاتصال تلقائيًا…",
    fcReconnecting: "جارٍ إعادة الاتصال بالغرفة…",
    fcSyncingStart: "تأكد توافق اللعبة. جارٍ مزامنة حالة البدء المشتركة…",
    fcSyncDelayed: "تأخرت حالة فاميكوم المشتركة. أبقِ اللاعبين داخل اللعبة، وتحقق من ملف .nes نفسه، ثم أعد بدء جلسة الغرفة.",
    fcWaitingConfirm: "بانتظار تأكيد اللاعب الآخر لملف اللعبة والنواة.",
    fcSyncingFromHost: "جارٍ مزامنة حالة فاميكوم المشتركة من المضيف…",
    fcRoomError: "أبلغت الغرفة عن خطأ أثناء تجهيز NetPlay لفاميكوم.",
    fcNetplayPrepareError: "تعذر تجهيز اتصال NetPlay.",
    fcLoadingLocal: "جارٍ تحميل اللعبة محليًا على هذا الجهاز…",
    fcRunningLocal: "تعمل اللعبة محليًا. اربط اللاعب الآخر بعد اختياره اللعبة نفسها.",
    fcFileError: "تعذر تشغيل هذا الملف. جرّب ملف .nes متوافقًا آخر.",
    fcPreparingRoom: "جارٍ تجهيز اتصال الغرفة…",
    fcConnectingHost: "جارٍ الاتصال بالمضيف…",
    fcReserveError: "تعذر حجز اتصال الغرفة. حاول مجددًا بعد دقيقة.",
    fcHostNotReady: "المضيف غير جاهز بعد. اطلب منه الاتصال أولًا.",
    fcRoomReady: "اتصال الغرفة جاهز. انتظر اتصال اللاعب الثاني.",
    fcNetplayStartError: "تعذر بدء NetPlay على هذا الاتصال. حدّث المتصفح وحاول مرة أخرى.",
    fcMarkedReady: "يُعد ملف لعبتك جاهزًا. انتظر اللاعب الآخر ثم يبدأ المضيف الجلسة.",
    fcVerifyingBoth: "جارٍ التحقق من الملف والنواة على الجهازين قبل البدء…",
    fcSessionActive: "جلسة اللاعبين نشطة. المضيف هو اللاعب 1 والضيف هو اللاعب 2.",
    fcConfirmingRole: "جارٍ تأكيد دور هذا الجهاز في الغرفة. انتظر لحظة ثم اضغط الزر مرة أخرى.",
    fcStateSaved: "حُفظت حالة اللعبة محليًا.",
    fcSaveReturn: "حفظ والعودة إلى إعدادات المحاكي",
    fcBackToRoom: "العودة إلى الغرفة",
    fcSaveControls: "حفظ الأزرار",
    fcConfigureControls: "تهيئة الأزرار",
    fcOpeningSettings: "جارٍ فتح الإعدادات…",
    fcControllerSettings: "إعدادات وحدة التحكم",
    fcEyebrow: "فاميكوم · لعب جماعي",
    fcGamePlayer: "مشغل الألعاب",
    fcSubtitle: "اختر ملف .nes نفسه على الجهازين. يبقى الملف محليًا ولا يرفعه Moudie NetPlay أو يشاركه مطلقًا.",
    fcNoGame: "لم يتم اختيار لعبة",
    fcEditMode: "وضع التعديل: اسحب أو غيّر حجم الأزرار وشريط الأدوات وشاشة اللعبة لهذا الاتجاه، ثم احفظ وعُد.",
    fcScreen: "الشاشة",
    fcLocal: "محلي",
    fcChangeFile: "تغيير ملف اللعبة",
    fcChooseNes: "1. اختر ملف .nes",
    fcLocalFile: "ملف محلي",
    fcScreenControls: "شاشة المحاكي والأزرار",
    fcConfigureScreen: "تهيئة الأزرار والشاشة",
    fcLocalSave: "حفظ محلي",
    fcLoadSave: "تحميل الحفظ",
    fcNetplayStatus: "حالة اللعب الجماعي",
    fcPrepareHost: "2. تجهيز اتصال الغرفة",
    fcConnectOther: "2. الاتصال باللاعب الآخر",
    fcConnectChannel: "2. توصيل قناة NetPlay",
    fcOtherConnected: "اللاعب الآخر متصل",
    fcWaitingOther: "بانتظار اللاعب الآخر",
    fcReadyConfirmed: "تم تأكيد الجاهزية",
    fcReady3: "3. جاهز",
    fcStartSession: "4. بدء الجلسة المتزامنة",
    fcVerifiedWait: "تم التحقق. انتظر بدء المضيف للجلسة.",
    fcChatHint: "اكتب رسالة إلى اللاعب الآخر.",
    fcLocalControls: "أزرار محلية",
    fcControls: "الأزرار",
    fcControlsAfterStart: "تظهر الأزرار بعد بدء المضيف للعب",
    fcResetGame: "إعادة اللعبة",
    fcHowToPlay: "طريقة اللعب",
    fcHowWeb: "يتطلب NetPlay في المتصفح اتصالًا مستقرًا ونفس ملف اللعبة على الجانبين.",
    fcHowNative: "اختر ملف .nes نفسه، ووصّل قناة NetPlay على الجهازين، ثم ليبدأ المضيف الجلسة. أزرار المضيف هي اللاعب 1 وأزرار الضيف هي اللاعب 2.",
    pspInitialStatus: "اختر ملف PSP القانوني نفسه على الجهازين.",
    pspChannelConnected: "قناة الغرفة متصلة. اختر ملفك المحلي ثم أكّد الجاهزية.",
    pspChannelDisconnected: "انقطعت قناة الغرفة. جارٍ إعادة الاتصال تلقائيًا…",
    pspAllReady: "جميع اللاعبين النشطين جاهزون. جارٍ فتح مشغل PSP المتزامن…",
    pspWaitingVerify: "بانتظار تحقق اللاعب الآخر من الملف نفسه.",
    pspCheckingFingerprint: "جارٍ فحص بصمة ملف PSP المحلي…",
    pspPreparingCore: "جارٍ تجهيز نواة PSP والملف المحلي الآن لبدء متزامن سريع…",
    pspCacheReady: "الملف والنواة وذاكرة التشغيل المحلية جاهزة. اضغط جاهز بعد أن يختار كل لاعب نشط الملف نفسه.",
    pspPickSupported: "اختر ملف PSP قانونيًا مدعومًا من هذا الجهاز.",
    pspReadyConfirmed: "تأكدت الجاهزية. يمكن للمضيف البدء عندما يستخدم جميع اللاعبين النشطين الملف نفسه.",
    pspCheckingBoth: "جارٍ فحص ملفي PSP والنواة قبل البدء المشترك…",
    pspChip: "غرفة PSP",
    pspEyebrow: "نواة PPSSPP · لعب جماعي للغرفة",
    pspSubtitle: "يختار كل لاعب ملف PSP القانوني المحلي نفسه. تتحقق الغرفة من بصمته دون رفع اللعبة.",
    pspRoomConnected: "الغرفة متصلة",
    pspConnecting: "جارٍ الاتصال",
    pspSpectatorWait: "مشاهد أو بانتظار مقعد لاعب",
    pspChangeGame: "تغيير لعبة PSP",
    pspChooseGame: "1. اختر لعبة PSP",
    pspSettingsHint: "جهّز تخطيطًا منفصلًا للوضع العمودي والأفقي قبل اللعب. لا تظهر أدوات التعديل وتغيير الحجم أثناء المباراة أبدًا.",
    pspConfigurePortrait: "تهيئة أزرار الوضع العمودي",
    pspConfigureLandscape: "تهيئة أزرار الوضع الأفقي",
    pspReady2: "2. جاهز",
    pspStartSession: "3. بدء جلسة PSP المتزامنة",
    pspRoomControls: "أزرار الغرفة",
    pspRoomControlsText: "تبقى الدردشة والميكروفون أعلى المشغل في الوضع الأفقي. يبقى المشاهدون في الغرفة للصوت والدردشة النصية.",
    p1InitialStatus: "اختر ملف لعبة PS1 من جهازك. يبقى الملف محليًا ولا يُرفع أبدًا.",
    p1AllReady: "جميع اللاعبين النشطين جاهزون. جارٍ فتح مشغل PS1 في وقت البدء المشترك…",
    p1CheckingFingerprint: "جارٍ فحص بصمة ملف PS1 المحلي للتحقق من أن اللاعب الآخر اختار الملف نفسه…",
    p1PreparingCore: "جارٍ تجهيز نواة PS1 والملف المحلي الآن لبدء متزامن سريع…",
    p1FingerprintReady: "الملف ونواة PS1 والبصمة جاهزة. اضغط جاهز لبدء متزامن سريع.",
    p1MarkedReady: "يُعد ملف لعبتك جاهزًا. انتظر جميع اللاعبين النشطين ثم يمكن للمضيف بدء الجلسة.",
    p1CheckingBoth: "جارٍ فحص ملف اللعبة والنواة لكل لاعب نشط قبل إرسال إشارة البدء…",
    p1NetplayPreparing: "جارٍ تجهيز PS1 NetPlay وتعيين هذا الجهاز داخل الغرفة…",
    p1LocalPreparing: "جارٍ تجهيز ملف اللعبة وفتح PCSX-ReARMed…",
    p1NetplayOpen: "مشغل PS1 مفتوح ومرتبط بالغرفة. انتظر رسالة التحقق داخل اللعبة.",
    p1LocalOpen: "المشغل المحلي مفتوح. العودة من اللعبة تعيدك إلى هذه الغرفة.",
    p1StartErrorBody: "تعذر تشغيل مشغل PS1.",
    p1Title: "مشغل PlayStation 1",
    p1Subtitle: "لعب محلي داخل Moudie NetPlay. لا يتضمن التطبيق ألعابًا أو ملفات BIOS؛ استخدم فقط الملفات التي تملك حق استخدامها.",
    p1ReadyPreview: "جاهز للمشغل الأصلي",
    p1FormatsPreview: "يدعم BIN وISO وCHD وPBP",
    p1ChangeFile: "تغيير ملف لعبة PS1",
    p1ChooseFile: "1. اختر ملف لعبة PS1",
    p1ScreenSettings: "إعدادات الشاشة ووحدة التحكم",
    p1ScreenSettingsText: "اختر التخطيط أولًا ثم افتح معايرة الأزرار. كل اتجاه وزر إجراء ودردشة وميكروفون وملف شاشة يُحفظ منفصلًا للوضع العمودي والأفقي.",
    p1OpenLocal: "فتح مشغل PS1 المحلي",
    p1NetplayTitle: "PS1 NetPlay",
    p1NetplayAllMatch: "اختار جميع اللاعبين النشطين اللعبة نفسها. أنت اللاعب",
    p1NetplayWaiting: "بانتظار الجاهزية وملف متطابق",
    p1ConfirmingStart: "جارٍ تأكيد البدء…",
    p1StartAll: "3. تشغيل PS1 للجميع",
    p1WaitingHost: "بانتظار بدء المضيف",
    p1PlayerStatus: "حالة مشغل PS1",
    p1CheckingCore: "جارٍ فحص النواة المحلية…",
    p1BiosStatus: "حالة BIOS",
    p1CheckingBios: "جارٍ فحص BIOS المحلي…",
    p1BiosNote: "قد تبدأ بعض الألعاب بـ HLE، لكن BIOS المحلي المتوافق يحسّن توافق PCSX-ReARMed ويساعد في تشخيص الألعاب التي تفشل في البدء.",
    p1AddBios: "إضافة BIOS محلي قانوني",
    p1BetaLimit: "حد النسخة التجريبية الحالي",
    p1BetaText: "لا يبدأ PS1 NetPlay إلا عندما يستخدم كل لاعب نشط في الغرفة ملفًا بالبصمة نفسها. لا تُرفع اللعبة أبدًا؛ تنقل الغرفة مدخلات وحدة التحكم وحالة ابتدائية صغيرة فقط.",
    segInitialStatus: "اختر الملف المحلي نفسه على الجهازين.",
    segWaitingOther: "بانتظار اللاعب الآخر.",
    segCoreNotReady: "نواة Android هذه غير جاهزة.",
    segCheckingFingerprint: "جارٍ فحص بصمة ملف اللعبة المحلي…",
    segPreparingCore: "جارٍ تجهيز نواة المحاكي والملف المحلي الآن لبدء متزامن سريع…",
    segRoom: "غرفة",
    segCopy: "اختر ملف اللعبة المحلي المطابق على جهازين. يتحقق Moudie من البصمة ويزامن حالة البدء ثم يرحّل مدخلات الأزرار وتحديثات الحالة فقط.",
    segSpectatorSlot: "مشاهد / لا يوجد مقعد لاعب نشط",
    segChooseFile: "1. اختر ملف اللعبة",
    segStartSession: "3. بدء الجلسة المتزامنة",
    introBootLabel: "مقدمة تشغيل Moudie NetPlay",
    introLoading: "جارٍ التحميل…",
    introSkip: "تخطي المقدمة",
  },
  fr: {
    lobby: "Accueil",
    library: "Bibliothèque",
    settings: "Réglages",
    localPlay: "JEU LOCAL",
    chooseSystem: "Choisissez votre système",
    profile: "Profil et préférences",
    username: "NOM D’UTILISATEUR",
    userId: "IDENTIFIANT",
    save: "ENREGISTRER",
    share: "PARTAGER L’IDENTIFIANT",
    language: "LANGUE",
    title: "Votre lobby de jeux classiques",
    choose: "Choisissez l’un des quatre émulateurs.",
    changePhoto: "CHANGER LA PHOTO",
    newPlayer: "Nouveau joueur",
    about: "À PROPOS DE CLASSIC ERA BY MOUDIE",
    policy: "POLITIQUE DU PROGRAMME",
    privacyPolicy: "POLITIQUE DE CONFIDENTIALITÉ",
    community: "REJOINDRE NOTRE COMMUNAUTÉ (BIENTÔT)",
    contact: "NOUS CONTACTER",
    help: "AIDE ET SUPPORT",
    suggestions: "SUGGESTIONS",
    localPrivacy: "CONFIDENTIALITÉ LOCALE",
    privacyText: "Les identifiants de salle et votre avatar restent sur cet appareil. Les fichiers de jeu ne sont pas envoyés à notre service.",
    nameShort: "Nom trop court",
    nameShortText: "Saisissez au moins deux caractères.",
    saved: "Enregistré",
    savedText: "Votre identité est prête pour les demandes d’amis.",
    pendingText: "Cette section sera reliée au service officiel avant le lancement public.",
    shareText: "Ajoutez-moi sur Classic Era by Moudie. Mon identifiant est",
    roomChat: "CHAT DE SALLE",
    send: "ENVOYER",
    voice: "VOIX DE SALLE",
    micOn: "MICRO ACTIVÉ",
    micOff: "MICRO DÉSACTIVÉ",
    speakerOn: "HAUT-PARLEUR ACTIVÉ",
    speakerOff: "HAUT-PARLEUR DÉSACTIVÉ",
    preparingVoice: "Préparation de la voix…",
    connectChat: "Connectez-vous au canal pour activer le chat.",
    writeMessage: "Écrire un message…",
    publicName: "Nom public du joueur",
    createRoomError: "Impossible de créer la salle",
    tryAgain: "Réessayez.",
    hostPublicLobby: "HÉBERGER LE LOBBY PUBLIC",
    createPrivateRoom: "CRÉER UNE SALLE PRIVÉE",
    chooseEmulator: "CHOISIR UN ÉMULATEUR",
    displayName: "NOM AFFICHÉ",
    voiceShort: "VOIX",
    chatShort: "CHAT",
    spectateShort: "SPECTATEUR",
    createRoomEnter: "CRÉER LA SALLE ET JOUER",
    checkCode: "Vérifiez le code",
    roomCodeLength: "Le code de salle contient six lettres ou chiffres.",
    addDisplayName: "Ajoutez un nom affiché",
    joinError: "Impossible de rejoindre",
    checkCodeAndRetry: "Vérifiez le code et réessayez.",
    joinPrivateRoom: "REJOINDRE UNE SALLE PRIVÉE",
    roomCode: "CODE DE SALLE",
    joinAs: "COMMENT REJOINDRE ?",
    player: "JOUEUR",
    controlGame: "Vous contrôlez le jeu",
    spectator: "SPECTATEUR",
    watchTalkChat: "Regarder, parler et discuter",
    joinRoom: "REJOINDRE LA SALLE",
    createPrivateForFriends: "CRÉER UNE SALLE PRIVÉE POUR AMIS",
    readyError: "Impossible de confirmer la préparation",
    unsupportedFile: "Fichier non pris en charge",
    chooseFamicomFile: "Choisissez un jeu Famicom légal avec l’extension .nes.",
    choosePs1File: "Choisissez un fichier PS1 complet .bin, .iso, .chd ou .pbp. Un fichier CUE seul n’est pas accepté car il nécessite son fichier BIN associé.",
    choosePspFile: "Choisissez un fichier PSP ISO, CSO, CHD ou PBP.",
    unsupportedGameFile: "Impossible de lire le fichier sélectionné.",
    androidRequired: "APK Android requis",
    ps1AndroidOnly: "Le lecteur PS1 natif fonctionne dans l’APK Android et n’est pas disponible dans l’aperçu web.",
    pspAndroidOnly: "Le lecteur PSP natif est disponible uniquement dans l’APK Android.",
    biosAndroidOnly: "La vérification et l’installation locale du BIOS sont disponibles uniquement dans l’APK Android.",
    biosAdded: "BIOS ajouté",
    biosStored: "Le fichier BIOS a été enregistré localement dans l’application. Il n’est jamais envoyé ni partagé.",
    biosAddError: "Impossible d’ajouter le BIOS",
    biosLegalDump: "Choisissez une copie légale avec un nom pris en charge.",
    chooseFileError: "Impossible de choisir le fichier",
    chooseGameError: "Impossible de choisir le jeu",
    choosePspGameError: "Impossible de choisir le jeu PSP",
    startGameError: "Impossible de démarrer le jeu",
    startPspError: "Impossible de démarrer la PSP",
    startPs1Error: "Impossible de démarrer le lecteur PS1",
    ps1GameError: "Réessayez et choisissez un fichier de jeu dans le stockage.",
    famicomGameError: "Essayez un autre fichier de jeu Famicom.",
    noSavedState: "Aucun état sauvegardé",
    noSavedStateText: "Démarrez le jeu, puis appuyez sur Sauvegarde locale pour créer un état sauvegardé.",
    focusModeError: "Impossible d’ouvrir le mode focus",
    sessionStartError: "La session n’a pas démarré",
    waitPlayersReady: "Attendez que les deux joueurs soient prêts.",
    ps1NetplayNeedsPlayers: "PS1 NetPlay exige que tous les joueurs actifs (2–8) sélectionnent le même fichier de jeu complet et le même cœur.",
    pspNetplayNeedsSeat: "PSP NetPlay nécessite un siège joueur attribué et une session vérifiée.",
    readGameError: "Impossible de lire le fichier de jeu depuis le stockage.",
    readBrowserGameError: "Impossible de lire le fichier de jeu dans le navigateur.",
    prepareEmulatorError: "Impossible de préparer l’écran de l’émulateur.",
    waitOtherPlayer: "Attendez que l’autre joueur se connecte au canal de la salle.",
    connectionIncomplete: "La connexion entre les deux appareils n’est pas encore terminée.",
    androidRoomOnly: "La vérification de la salle est disponible uniquement dans l’APK Android.",
    netplayNeedsSeat: "Cette salle nécessite un siège joueur attribué et une session multijoueur vérifiée.",
    brandName: "Classic Era by Moudie",
    slogan: "L’ancien vaut l’or",
    voiceMode: "MODE VOIX",
    voicePushToTalk: "PUSH-TO-TALK",
    voiceOpenMic: "MICRO OUVERT",
    voiceChannel: "CANAL VOIX",
    voiceChannelRoom: "SALLE",
    voiceChannelTeam: "ÉQUIPE",
    voiceHoldToTalk: "MAINTENIR POUR PARLER",
    voiceTeamNote: "Les spectateurs écoutent seulement dans le canal équipe.",
    voiceConnectedRoom: "Voix de la salle connectée — tout le monde peut parler.",
    voiceConnecting: "Connexion de la voix…",
    voiceReadyMuted: "Voix prête — micro désactivé.",
    voiceWaitingRoom: "La voix attend la connexion à la salle.",
    voiceMicPermission: "L’autorisation du micro est requise pour la voix.",
    voiceBuiltInReady: "Voix intégrée active.",
    voiceSetupFailed: "Échec de la configuration du canal voix.",
    voiceSfuUnavailable: "SFU vocal indisponible — utilisation du canal intégré.",
    voicePermissionTitle: "Voix de salle",
    voicePermissionMessage: "Classic Era a besoin du micro pour le canal vocal de la salle.",
    voiceAllow: "Autoriser",
    homeRetro: "JEUX CLASSIQUES, À VOTRE FAÇON",
    homeIntro: "Choisissez d’abord un mode de jeu. Sélectionnez votre émulateur, votre fichier de jeu local et vos réglages uniquement quand vous êtes prêt à jouer.",
    homeLocalText: "Choisissez un système et jouez à votre fichier de jeu légal sur cet appareil, sans connexion en ligne.",
    homePublicLobby: "LOBBY PUBLIC",
    homeCreateText: "Trouvez un lobby classique ouvert ou hébergez-en un pour 4 joueurs et 4 spectateurs maximum (la NES : 2 joueurs et 6 spectateurs).",
    homeJoinText: "Saisissez un code d’invitation simple de vos amis, puis choisissez le mode joueur ou spectateur.",
    homeTip: "Avant de commencer une partie, utilisez les réglages de manette et d’écran pour enregistrer des dispositions distinctes en portrait et en paysage.",
    homeBrandSub: "QUATRE SYSTÈMES · NETPLAY",
    homeOpenSettings: "Ouvrir les réglages",
    libTitle: "Systèmes et cœurs",
    libSubtitle: "Choisissez d’abord un mode de jeu, puis l’un des quatre systèmes pris en charge pour votre salle ou session locale.",
    libPspDescription: "Choisissez un fichier de jeu PSP légal depuis le jeu local ou une salle PSP. Les sauvegardes rapides restent sur cet appareil.",
    libNesDescription: "La session de salle démarre après que les joueurs ont vérifié le même jeu et un cœur compatible.",
    libSegaDescription: "Choisissez un jeu Sega légal en jeu local. Vos sauvegardes et votre disposition de manette restent sur cet appareil.",
    libPs1Description: "Sauvegardes locales, prise en charge ISO et commandes personnalisées disponibles dans le lecteur PS1.",
    libSaveReady: "SAUVEGARDE LOCALE PRÊTE",
    libSaveLocalOnly: "SAUVEGARDE LOCALE UNIQUEMENT",
    libReady: "PRÊT",
    libNoticeTitle: "VOS FICHIERS RESTENT LOCAUX",
    libNoticeText: "Moudie NetPlay coordine uniquement les salles et les vérifications de compatibilité. Il n’inclut aucun jeu et ne transfère pas vos fichiers à d’autres joueurs.",
    commonBack: "Retour",
    localSubtitle: "Sélectionnez l’un des quatre émulateurs. Vos fichiers de jeu, sauvegardes et dispositions de manette restent sur cet appareil.",
    localNotice: "Chaque émulateur prend en charge des dispositions distinctes en portrait et paysage. Utilisez MODIFIER pour déplacer un bouton, puis TAILLE − / + ou le pincement pour le redimensionner.",
    lbLoadError: "Impossible de charger les lobbies publics",
    lbLoadErrorBody: "Essayez d’actualiser dans un instant.",
    lbNameAlert: "Ajoutez un nom affiché",
    lbNameAlertBody: "Saisissez au moins deux caractères avant de rejoindre un lobby public.",
    lbJoinError: "Impossible de rejoindre le lobby public",
    lbJoinErrorBody: "Actualisez la liste des lobbies et réessayez.",
    lbTitle: "LOBBY PUBLIC",
    lbFindSession: "TROUVER UNE SESSION CLASSIQUE",
    lbHeroText: "Rejoignez un lobby ouvert. Les systèmes standards acceptent 4 joueurs et 4 spectateurs ; la NES : 2 joueurs et 6 spectateurs.",
    lbDisplayName: "VOTRE NOM AFFICHÉ",
    lbExample: "Exemple : Alex",
    lbJoinAs: "REJOINDRE EN TANT QUE",
    lbOpenLobbies: "LOBBIES OUVERTS",
    lbRefresh: "ACTUALISER",
    lbChecking: "Recherche des lobbies ouverts…",
    lbNoneYet: "AUCUN LOBBY OUVERT POUR L’INSTANT",
    lbNoneText: "Hébergez la première session publique, ou demandez un code de salle privée à un ami.",
    lbPlayersShort: "JOUEURS",
    lbSpectatorsShort: "SPECTATEURS",
    lbReadyShort: "PRÊTS",
    lbJoinBtn: "REJOINDRE",
    lbFull: "COMPLET",
    crDefaultLobbyName: "Lobby classique",
    crDefaultSessionName: "Session entre amis",
    crFallbackHost: "Joueur",
    crPublicSub: "Les lobbies publics sont visibles par système et places libres. Les codes d’invitation restent privés.",
    crPrivateSub: "Choisissez le système de jeu. Chaque système dispose d’une disposition de manette dédiée dans le lecteur.",
    crLobbyName: "NOM DU LOBBY",
    crRoomName: "NOM DE LA SALLE",
    crLobbyExample: "Exemple : Rétro du week-end",
    crRoomExample: "Exemple : Course du vendredi soir",
    crFriendsVisible: "Visible par vos amis",
    crCapacityTitle: "CAPACITÉ DE LA SALLE",
    crMembersShort: "MEMBRES",
    crActivePlayersShort: "JOUEURS ACTIFS",
    crSpectatorsShort: "SPECTATEURS",
    crNoteNes: "La Famicom est limitée à deux sièges de manette actifs. Les autres membres peuvent regarder, parler et discuter sans occuper un siège.",
    crNoteStd: "La salle sépare le jeu actif des spectateurs pour réduire la pression de synchronisation. Les spectateurs regardent, parlent et discutent sans occuper un siège.",
    jrPrivacyNote: "Votre code de salle et votre adhésion restent sur cet appareil. Les fichiers de jeu ne sont jamais envoyés à la salle.",
    rmSharePrefix: "Rejoins-moi dans",
    rmShareCodeLabel: "Code de salle",
    rmOpenError: "Impossible d’ouvrir la salle",
    rmOpenErrorText: "Cette adhésion est peut-être enregistrée sur un autre appareil, ou la salle n’est plus disponible.",
    rmReturnLobby: "RETOUR À L’ACCUEIL",
    rmWaiting: "EN ATTENTE DES JOUEURS",
    rmActive: "SESSION ACTIVE",
    rmPrivateRoom: "SALLE PRIVÉE",
    rmInviteCode: "CODE D’INVITATION",
    rmShareCode: "PARTAGER LE CODE",
    rmMembers: "MEMBRES DE LA SALLE",
    rmHostBadge: "JOUEUR 1 · HÔTE",
    rmPlayerShort: "JOUEUR",
    rmSpectatorStatus: "Regarde et parle dans la salle",
    rmChecking: "Vérification de l’émulateur",
    rmEnterFamicom: "RÉGLAGES FAMICOM",
    rmEnterPs1: "RÉGLAGES PS1",
    rmEnterPsp: "RÉGLAGES PSP",
    rmEnterSega: "RÉGLAGES SEGA GENESIS",
    rmPrepTitle: "PRÉPARATION DU JOUEUR",
    rmPrepText: "Le chat texte et la voix sont disponibles pendant la préparation du lecteur de salle :",
    rmReadyOutOf: "PRÊTS SUR",
    playDone: "TERMINÉ",
    playEdit: "MODIFIER",
    playEditHint: "L’écran de jeu et chaque bouton sont indépendants. Déplacez ou redimensionnez chaque élément, puis enregistrez une disposition distincte pour ce système et cette orientation.",
    playOnlineRoom: "SALLE EN LIGNE",
    playPressed: "Bouton pressé :",
    playChatTitle: "CHAT TEXTE",
    playChatHintLocal: "Les messages locaux restent sur cet appareil.",
    playChatHintRoom: "Les messages de salle sont envoyés aux membres connectés.",
    playOpenChat: "Ouvrir le chat texte",
    lsShownInApk: "Visible dans l’APK Android",
    lsCoreRequired: "Cœur Android requis",
    lsInstallApk: "Installez l’APK Android complet pour exécuter cet émulateur.",
    lsSelectError: "Impossible de sélectionner un fichier de jeu.",
    lsUnexpected: "Une erreur inattendue est survenue à l’ouverture du fichier de jeu.",
    lsHeader: "BIBLIOTHÈQUE D’ÉMULATEURS",
    lsNesSubtitle: "Manette classique · Jusqu’à 4 sièges si pris en charge",
    lsPs1Subtitle: "PCSX-ReARMed · Sauvegardes rapides et édition complète des commandes",
    lsPspSubtitle: "PPSSPP · Profil réseau PSP pour les jeux pris en charge",
    lsSegaSubtitle: "Genesis Plus GX · Dispositions 3 ou 6 boutons",
    lsCheckingCore: "VÉRIFICATION DU CŒUR",
    lsCoreReady: "CŒUR PRÊT",
    lsDownloadsFirst: "TÉLÉCHARGEMENT AU PREMIER LANCEMENT",
    lsHowTitle: "FONCTIONNEMENT DE CET ÉMULATEUR",
    lsHowText: "Choisissez un fichier de jeu légal stocké sur votre appareil. Moudie n’envoie jamais votre jeu ni votre BIOS. Configurez les commandes portrait et paysage avant de jouer ; l’écran de jeu reste libre de tout outil de déplacement ou redimensionnement.",
    lsIsoNotice: "Le PS1 prend en charge les fichiers ISO ainsi que BIN, CUE, CHD et PBP.",
    lsExtPrefix: "Extensions prises en charge :",
    lsOrientations: "Le jeu en portrait et en paysage est pris en charge avec des dispositions de manette indépendantes.",
    lsSaveNote: "La sauvegarde/charge locale est disponible depuis la barre d’outils en jeu.",
    lsSettingsTitle: "RÉGLAGES DE L’ÉMULATEUR",
    lsPlayOrientation: "ORIENTATION DE JEU",
    lsScreenRatio: "RATIO D’ÉCRAN",
    lsPreparing: "PRÉPARATION DU JEU…",
    lsChooseStart: "CHOISIR LE JEU ET DÉMARRER",
    lsLegal: "En choisissant un fichier, vous confirmez avoir le droit de l’utiliser. Moudie n’inclut aucun ROM ni BIOS.",
    fcChooseGameFirst: "Choisissez d’abord un jeu",
    fcOtherVerified: "L’autre joueur a vérifié le fichier de jeu. L’hôte peut démarrer la session.",
    fcStateRestored: "Le dernier état de jeu local a été restauré.",
    fcStateRestoreError: "Impossible de restaurer le dernier état de jeu local.",
    fcStateSaving: "Enregistrement de l’état du jeu en local…",
    fcSetupOpen: "La configuration des commandes est ouverte pour cette orientation. Déplacez ou redimensionnez chaque bouton, puis enregistrez et revenez à PRÊT.",
    fcFocusErrorBody: "Impossible d’ouvrir le mode focus natif.",
    fcHostSynced: "L’hôte a synchronisé le démarrage du jeu.",
    fcSyncError: "Impossible de synchroniser le démarrage du jeu. Rechargez le fichier et reconnectez-vous à la salle.",
    fcDifferentFile: "L’autre joueur a un fichier de jeu ou une version de cœur différente.",
    fcVerified: "Compatibilité du jeu vérifiée. L’hôte peut démarrer la session à deux.",
    fcConnectedVerifying: "Connecté à l’autre appareil. Vérification du fichier de jeu…",
    fcConnectionClosed: "La connexion avec l’autre joueur a été fermée.",
    fcConnectionError: "Impossible de terminer la connexion. Vérifiez que l’autre joueur a ouvert le lecteur Famicom.",
    fcConnectingChannel: "Connexion au canal NetPlay de la salle…",
    fcChannelReady: "Le canal de la salle est prêt. Attendez que l’autre joueur rejoigne et choisisse le même fichier.",
    fcChannelError: "Impossible de se connecter à la salle. Vérifiez votre connexion Internet et réessayez.",
    fcInterrupted: "Connexion à la salle interrompue ; reconnexion automatique…",
    fcReconnecting: "Reconnexion à la salle…",
    fcSyncingStart: "Compatibilité confirmée. Synchronisation de l’état de départ partagé…",
    fcSyncDelayed: "L’état Famicom partagé tarde. Gardez les deux joueurs en jeu, vérifiez le même fichier .nes, puis relancez la session de salle.",
    fcWaitingConfirm: "En attente de la confirmation du fichier et du cœur par l’autre joueur.",
    fcSyncingFromHost: "Synchronisation de l’état Famicom partagé depuis l’hôte…",
    fcRoomError: "La salle a signalé une erreur pendant la préparation du NetPlay Famicom.",
    fcNetplayPrepareError: "Impossible de préparer la connexion NetPlay.",
    fcLoadingLocal: "Chargement du jeu en local sur cet appareil…",
    fcRunningLocal: "Le jeu tourne en local. Connectez l’autre joueur après qu’il a choisi le même jeu.",
    fcFileError: "Impossible de lancer ce fichier. Essayez un autre fichier .nes compatible.",
    fcPreparingRoom: "Préparation de la connexion de salle…",
    fcConnectingHost: "Connexion à l’hôte…",
    fcReserveError: "Impossible de réserver la connexion de salle. Réessayez dans une minute.",
    fcHostNotReady: "L’hôte n’est pas encore prêt. Demandez-lui de se connecter d’abord.",
    fcRoomReady: "La connexion de salle est prête. Attendez que le deuxième joueur se connecte.",
    fcNetplayStartError: "Impossible de démarrer NetPlay sur cette connexion. Mettez le navigateur à jour et réessayez.",
    fcMarkedReady: "Votre fichier de jeu est marqué prêt. Attendez l’autre joueur, puis l’hôte lance la session.",
    fcVerifyingBoth: "Vérification du fichier et du cœur sur les deux appareils avant le démarrage…",
    fcSessionActive: "La session à deux est active. L’hôte est le joueur 1 et l’invité le joueur 2.",
    fcConfirmingRole: "Confirmation du rôle de cet appareil dans la salle. Patientez un instant, puis appuyez à nouveau sur le bouton.",
    fcStateSaved: "État du jeu enregistré en local.",
    fcSaveReturn: "ENREGISTRER ET REVENIR AUX RÉGLAGES",
    fcBackToRoom: "RETOUR À LA SALLE",
    fcSaveControls: "ENREGISTRER LES COMMANDES",
    fcConfigureControls: "CONFIGURER LES COMMANDES",
    fcOpeningSettings: "OUVERTURE DES RÉGLAGES…",
    fcControllerSettings: "RÉGLAGES DE LA MANETTE",
    fcEyebrow: "FAMICOM · NETPLAY",
    fcGamePlayer: "LECTEUR DE JEU",
    fcSubtitle: "Choisissez le même fichier .nes sur les deux appareils. Le fichier reste local et n’est jamais envoyé ni partagé par Moudie NetPlay.",
    fcNoGame: "AUCUN JEU SÉLECTIONNÉ",
    fcEditMode: "Mode édition : déplacez ou redimensionnez les commandes, le HUD et l’écran de jeu pour cette orientation, puis enregistrez et revenez.",
    fcScreen: "ÉCRAN",
    fcLocal: "LOCAL",
    fcChangeFile: "CHANGER DE FICHIER DE JEU",
    fcChooseNes: "1. CHOISIR UN FICHIER .NES",
    fcLocalFile: "FICHIER LOCAL",
    fcScreenControls: "ÉCRAN ET COMMANDES DE L’ÉMULATEUR",
    fcConfigureScreen: "CONFIGURER COMMANDES ET ÉCRAN",
    fcLocalSave: "SAUVEGARDE LOCALE",
    fcLoadSave: "CHARGER LA SAUVEGARDE",
    fcNetplayStatus: "ÉTAT NETPLAY",
    fcPrepareHost: "2. PRÉPARER LA CONNEXION DE SALLE",
    fcConnectOther: "2. SE CONNECTER À L’AUTRE JOUEUR",
    fcConnectChannel: "2. CONNECTER LE CANAL NETPLAY",
    fcOtherConnected: "L’AUTRE JOUEUR EST CONNECTÉ",
    fcWaitingOther: "EN ATTENTE DE L’AUTRE JOUEUR",
    fcReadyConfirmed: "PRÉPARATION CONFIRMÉE",
    fcReady3: "3. PRÊT",
    fcStartSession: "4. DÉMARRER LA SESSION SYNCHRONISÉE",
    fcVerifiedWait: "VÉRIFIÉ. ATTENDEZ QUE L’HÔTE LANCE LA SESSION.",
    fcChatHint: "Écrivez un message à l’autre joueur.",
    fcLocalControls: "COMMANDES LOCALES",
    fcControls: "COMMANDES",
    fcControlsAfterStart: "LES COMMANDES APPARAISSENT QUAND L’HÔTE LANCE LA PARTIE",
    fcResetGame: "Réinitialiser le jeu",
    fcHowToPlay: "MODE D’EMPLOI",
    fcHowWeb: "Le NetPlay navigateur exige une connexion stable et le même fichier de jeu des deux côtés.",
    fcHowNative: "Choisissez le même fichier .nes, connectez le canal NetPlay sur les deux appareils, puis laissez l’hôte lancer la session. Les commandes de l’hôte sont le joueur 1 et celles de l’invité le joueur 2.",
    pspInitialStatus: "Choisissez le même fichier PSP légal sur les deux appareils.",
    pspChannelConnected: "Canal de salle connecté. Choisissez votre fichier local et marquez PRÊT.",
    pspChannelDisconnected: "Canal de salle déconnecté. Reconnexion automatique…",
    pspAllReady: "Tous les joueurs actifs sont prêts. Ouverture du lecteur PSP synchronisé…",
    pspWaitingVerify: "En attente de la vérification du même fichier par l’autre joueur.",
    pspCheckingFingerprint: "Vérification de l’empreinte du fichier PSP local…",
    pspPreparingCore: "Préparation du cœur PSP et du fichier local pour un démarrage synchronisé rapide…",
    pspCacheReady: "Fichier, cœur et cache de lancement local prêts. Appuyez sur PRÊT après que chaque joueur actif a sélectionné le même fichier.",
    pspPickSupported: "Choisissez un fichier PSP légal pris en charge sur cet appareil.",
    pspReadyConfirmed: "PRÊT confirmé. L’hôte peut démarrer quand tous les joueurs actifs utilisent le même fichier.",
    pspCheckingBoth: "Vérification des deux fichiers PSP et du cœur avant le démarrage partagé…",
    pspChip: "SALLE PSP",
    pspEyebrow: "CŒUR PPSSPP · NETPLAY DE SALLE",
    pspSubtitle: "Chaque joueur sélectionne le même fichier PSP légal local. La salle vérifie son empreinte sans envoyer le jeu.",
    pspRoomConnected: "SALLE CONNECTÉE",
    pspConnecting: "CONNEXION",
    pspSpectatorWait: "SPECTATEUR OU EN ATTENTE D’UN SIÈGE JOUEUR",
    pspChangeGame: "CHANGER DE JEU PSP",
    pspChooseGame: "1. CHOISIR UN JEU PSP",
    pspSettingsHint: "Configurez une disposition distincte en portrait et en paysage avant de jouer. Les outils d’édition et de redimensionnement n’apparaissent jamais pendant le match.",
    pspConfigurePortrait: "CONFIGURER LES COMMANDES PORTRAIT",
    pspConfigureLandscape: "CONFIGURER LES COMMANDES PAYSAGE",
    pspReady2: "2. PRÊT",
    pspStartSession: "3. DÉMARRER LA SESSION PSP SYNCHRONISÉE",
    pspRoomControls: "COMMANDES DE SALLE",
    pspRoomControlsText: "CHAT et MICRO restent en haut du lecteur en paysage. Les spectateurs restent dans la salle pour la voix et le chat texte.",
    p1InitialStatus: "Choisissez un fichier de jeu PS1 sur votre appareil. Le fichier reste local et n’est jamais envoyé.",
    p1AllReady: "Tous les joueurs actifs sont prêts. Ouverture du lecteur PS1 à l’heure de départ partagée…",
    p1CheckingFingerprint: "Vérification de l’empreinte du fichier PS1 local pour confirmer que l’autre joueur a sélectionné le même fichier…",
    p1PreparingCore: "Préparation du cœur PS1 et du fichier local pour un démarrage synchronisé rapide…",
    p1FingerprintReady: "Fichier, cœur PS1 et empreinte prêts. Appuyez sur PRÊT pour un démarrage synchronisé rapide.",
    p1MarkedReady: "Votre jeu est marqué prêt. Attendez tous les joueurs actifs, puis l’hôte peut lancer la session.",
    p1CheckingBoth: "Vérification du fichier et du cœur de chaque joueur actif avant l’envoi du signal de départ…",
    p1NetplayPreparing: "Préparation du PS1 NetPlay et attribution de cet appareil dans la salle…",
    p1LocalPreparing: "Préparation du fichier de jeu et ouverture de PCSX-ReARMed…",
    p1NetplayOpen: "Le lecteur PS1 est ouvert et lié à la salle. Attendez le message de vérification en jeu.",
    p1LocalOpen: "Le lecteur local est ouvert. Revenir depuis le jeu vous ramène à cette salle.",
    p1StartErrorBody: "Impossible de démarrer le lecteur PS1.",
    p1Title: "Lecteur PlayStation 1",
    p1Subtitle: "Jeu local dans Moudie NetPlay. L’application n’inclut ni jeux ni fichiers BIOS ; utilisez uniquement des fichiers dont vous avez légalement le droit.",
    p1ReadyPreview: "Prêt pour le lecteur natif",
    p1FormatsPreview: "Prend en charge BIN, ISO, CHD et PBP",
    p1ChangeFile: "CHANGER LE FICHIER PS1",
    p1ChooseFile: "1. CHOISIR UN FICHIER PS1",
    p1ScreenSettings: "RÉGLAGES D’ÉCRAN ET DE MANETTE",
    p1ScreenSettingsText: "Choisissez d’abord la disposition, puis ouvrez l’étalonnage des commandes. Chaque direction, bouton d’action, chat, micro et profil d’écran est enregistré séparément en portrait et en paysage.",
    p1OpenLocal: "OUVRIR LE LECTEUR PS1 LOCAL",
    p1NetplayTitle: "PS1 NetPlay",
    p1NetplayAllMatch: "Tous les joueurs actifs ont sélectionné le même jeu. Vous êtes le joueur",
    p1NetplayWaiting: "En attente de PRÊT et d’un fichier correspondant",
    p1ConfirmingStart: "CONFIRMATION DU DÉMARRAGE…",
    p1StartAll: "3. LANCER PS1 POUR TOUS",
    p1WaitingHost: "EN ATTENTE DU DÉMARRAGE PAR L’HÔTE",
    p1PlayerStatus: "ÉTAT DU LECTEUR PS1",
    p1CheckingCore: "Vérification du cœur local…",
    p1BiosStatus: "ÉTAT DU BIOS",
    p1CheckingBios: "Vérification du BIOS local…",
    p1BiosNote: "Certains jeux peuvent démarrer avec HLE, mais un BIOS local compatible améliore la compatibilité de PCSX-ReARMed et aide à diagnostiquer les jeux qui ne démarrent pas.",
    p1AddBios: "AJOUTER UN BIOS LOCAL LÉGAL",
    p1BetaLimit: "LIMITE BÊTA ACTUELLE",
    p1BetaText: "Le PS1 NetPlay démarre uniquement si chaque joueur actif de la salle utilise un fichier avec la même empreinte. Le jeu n’est jamais envoyé ; la salle transporte uniquement les entrées de manette et un petit état initial.",
    segInitialStatus: "Choisissez le même fichier local sur les deux appareils.",
    segWaitingOther: "En attente de l’autre joueur.",
    segCoreNotReady: "Ce cœur Android n’est pas prêt.",
    segCheckingFingerprint: "Vérification de l’empreinte du fichier de jeu local…",
    segPreparingCore: "Préparation du cœur d’émulateur et du fichier local pour un démarrage synchronisé rapide…",
    segRoom: "SALLE",
    segCopy: "Sélectionnez le même fichier de jeu local sur deux appareils. Moudie vérifie une empreinte, synchronise l’état de départ, puis relaie uniquement les entrées de manette et les mises à jour d’état.",
    segSpectatorSlot: "SPECTATEUR / AUCUN SIÈGE ACTIF",
    segChooseFile: "1. CHOISIR UN FICHIER DE JEU",
    segStartSession: "3. DÉMARRER LA SESSION SYNCHRONISÉE",
    introBootLabel: "Animation de démarrage Moudie NetPlay",
    introLoading: "CHARGEMENT…",
    introSkip: "PASSER",
  },
};
type LanguageContextValue = { language: AppLanguage; ready: boolean; setLanguage: (language: AppLanguage) => Promise<void>; t: (key: string) => string; isRTL: boolean };
const LanguageContext = createContext<LanguageContextValue | null>(null);
export function LanguageProvider({ children }: { children: ReactNode }) { const [language,setCurrentLanguage]=useState<AppLanguage>("en"); const [ready,setReady]=useState(false); useEffect(()=>{ AsyncStorage.getItem(STORAGE_KEY).then(v=>{if(v==="ar"||v==="en"||v==="fr")setCurrentLanguage(v);}).catch(()=>undefined).finally(()=>setReady(true));},[]); const setLanguage=useCallback(async(next:AppLanguage)=>{setCurrentLanguage(next);await AsyncStorage.setItem(STORAGE_KEY,next);},[]); const t=useCallback((key:string)=>dictionaries[language][key]??dictionaries.en[key]??key,[language]); const value=useMemo(()=>({language,ready,setLanguage,t,isRTL:language==="ar"}),[language,ready,setLanguage,t]); return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>; }
export function useLanguage(){const value=useContext(LanguageContext);if(!value)throw new Error("useLanguage must be used inside LanguageProvider");return value;}
export const languageKeys = Object.keys(dictionaries.en);
